name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build step
        run: deno task dev

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "coolwallpaper4329978" # Replace with your actual project name
          entrypoint: "main.ts"
